# Ref https://github.com/cross-rs/cross/blob/main/docs/custom_images.md#adding-dependencies-to-existing-images
# `cross` is installed in CI via a gh action for speed, which can end up using an old version of cross.
# The version of the cross-image is within each release of cross, so for example I saw the
# 'aarch64-unknown-linux-gnu' image using ubuntu xenial which is ancient

# Each target has an override to use the latest image off `main`
[target.aarch64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-gnu:main"

[target.aarch64-unknown-linux-musl]
image = "ghcr.io/cross-rs/aarch64-unknown-linux-musl:main"

[target.x86_64-unknown-linux-gnu]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-gnu:main"

[target.x86_64-unknown-linux-musl]
image = "ghcr.io/cross-rs/x86_64-unknown-linux-musl:main"

[target.x86_64-apple-darwin]

[target.aarch64-apple-darwin]